apiVersion: v3
kind: service
metadata:
  name: code-security-team-tag-test-2
  owner: tee-team
datadog:
  codeLocations:
    - repositoryURL: https://github.com/eoghanm2013/code-security-team-tag-test-2.git
      paths:
        - "**"
spec:
  type: web
  languages:
    - javascript
